
services:
  - type: web
    name: audiogod-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: false
