services:
  - type: web
    name: audiogod-bot
    env: docker
    plan: free  # optional, makes sure you stay on free plan
    buildCommand: |
      ./build.sh
      pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: false  # set to true if you want auto-deploy on push
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FFMPEG_BIN
        value: ffmpeg
